stages:
  data_validation:
    cmd: python src/step2_training_Data_Validation.py
    deps:
      - src/step2_training_Data_Validation.py
  data_processing1:
    cmd: python src/step3_data_preprocessing_stage1.py
    deps:
      - Data/Raw_data/ThyroidRawData.csv
      - src/step3_data_preprocessing_stage1.py
    outs:
      - Data/interm1/ThyroidInterm1Data.csv
      - Data/interm2/ThyroidInterm2Data.csv
      - Data/Processed_stage1/ThyoidProcessedStage1Data.csv
  data_processing2:
    cmd: python src/step4_data_preprocessing_stage2.py
    deps:
      - Data/Processed_stage1/ThyoidProcessedStage1Data.csv
      - src/step4_data_preprocessing_stage2.py
    outs:
      - Data/Processed_stage2/X_train.csv
      - Data/Processed_stage2/X_val.csv
      - Data/Processed_stage2/y_train.csv
      - Data/Processed_stage2/y_val.csv
      - preprocess_pipeline/preprocess_pipeline.pkl
      - preprocess_pipeline/le_transforme.pkl
  model_training:
    cmd: python src/step5_model_training.py
    deps:
      - Data/Processed_stage2/X_train.csv
      - Data/Processed_stage2/X_val.csv
      - Data/Processed_stage2/y_train.csv
      - Data/Processed_stage2/y_val.csv
      - src/step5_model_training.py
    outs:
      - Metrics/metrics.json
      - Metrics/classification_report.csv
      - Models/model.joblib

